// Ledger & Crown — practice. Maud sets one small problem a day on the player's OWN books (a number you can find in the Ledger, the forecast or a live offer), and when two
// offers are on the table she asks which one really puts more Cash in the chest. Practising on different days is the only way to turn "introduced" into "mastered", so each
// right answer on your own is recorded as evidence in the transcript (and a hint or a walk-through isn't). A right answer also earns a favour; favours unlock the parts of
// Maud's story she keeps back. Pure functions of the game state: nothing here posts to the books, and every answer is computed from the same engine the game runs on.
window.Practice = (function () {
  const S = typeof Spring !== "undefined" ? Spring : window.Spring, B = typeof Books !== "undefined" ? Books : window.Books;
  const hash = s => { let h = 5381; for (let i = 0; i < s.length; i++) h = (h * 33 + s.charCodeAt(i)) >>> 0; return h; };
  const r1 = x => Math.round(x * 10) / 10, pct = x => Math.round(x * 100), fmtList = a => a.join(", ");
  const lastSale = s => { for (let i = s.journal.length - 1; i >= 0; i--) { const j = s.journal[i]; if (j.type === "sale" && j.lines.revenue < 0) { const k = s.journal[i + 1]; if (k && k.type === "cogs") return { rev: -j.lines.revenue, cost: k.lines.cogs, sacks: k.lines.cogs / S.R.unitCost, who: j.memo }; } } return null; };
  const nextPayday = s => { const d = S.nextWeekEnd(s); return d >= s.day ? d : null; };
  // ---- the bank: each returns a problem or null when it doesn't apply today. answer is a number; tol the allowed slack.
  const BANK = [
    { id: "gross", concept: "gross", make: s => { const l = lastSale(s); if (!l || l.rev <= 0) return null;
        return { text: `Your last sale brought in <b>${l.rev}</b> and the grain in it cost you <b>${l.cost}</b>. What's your gross margin, in %?`, answer: pct((l.rev - l.cost) / l.rev), tol: 1, hints: ["Gross profit is Revenue minus the cost of what you sold.", "Margin divides that profit by the price (the Revenue), not by the cost."], work: `(${l.rev} − ${l.cost}) ÷ ${l.rev} = ${r1((l.rev - l.cost) / l.rev)}, so ${pct((l.rev - l.cost) / l.rev)}%.`, docs: ["ledger"] }; } },
    { id: "markup", concept: "margin", make: s => { const p = S.marketPrice(s.day), c = S.R.unitCost; return { text: `A sack costs you <b>${c}</b>, and today the going price is <b>${p}</b>. What's your <b>markup</b> on a sack, in %?`, answer: pct((p - c) / c), tol: 1,
        hints: ["Markup divides the profit by what the sack cost you.", "Not the price: that would be the margin."], work: `Profit ${p} − ${c} = ${p - c}; ${p - c} ÷ ${c} = ${r1((p - c) / c)}, so ${pct((p - c) / c)}%. (Margin would be ${pct((p - c) / p)}%.)`, docs: [] }; } },
    { id: "interest", concept: "tvm", make: s => { const t = S.terms(s), l = -s.bal.loan; if (l <= 0) return null; const w = Math.round(l * t.rateBp / 10000);
        return { text: `You owe Ezra <b>${l}</b> at <b>${t.rateBp / 100}%</b> a week. How much interest do you pay at the next pay-day?`, answer: w, tol: 0, hints: ["Interest = the loan × the weekly rate.", `${t.rateBp / 100}% is ${t.rateBp / 100} per hundred.`], work: `${l} × ${t.rateBp / 100}% = ${l * t.rateBp / 10000}, which rounds to ${w}.`, docs: [] }; } },
    { id: "payday", concept: "wc", make: s => { const d = nextPayday(s); if (d == null || d - s.day > 6) return null; const rows = S.forecast(s, d - s.day + 1); if (!rows.length) return null;
        const cin = rows.reduce((a, r) => a + r.cin, 0), cout = rows.reduce((a, r) => a + r.cout, 0), close = rows[rows.length - 1].close;
        return { text: `Cash is <b>${s.bal.cash}</b>. Between now and the end of day <b>${d}</b>, <b>${cin}</b> comes in and <b>${cout}</b> goes out (wages, interest, bills). If you do nothing else, what's your Cash at the end of day ${d}?`,
          answer: close, tol: 0, hints: ["Start with today's Cash, add what comes in, take away what goes out.", "The forecast board has the same numbers, day by day."], work: `${s.bal.cash} + ${cin} − ${cout} = ${close}.`, docs: ["forecast"] }; } },
    { id: "discount", concept: "ap", make: s => { const b = s.bills.find(x => S.discNow(s, x) > 0); if (!b) return null; const d = S.discNow(s, b);
        return { text: `Tomas's bill is <b>${b.amount}</b>, with <b>2%</b> off if you pay by day ${b.discBy}. It's day ${s.day}. How much Cash do you pay him if you pay now?`, answer: b.amount - d, tol: 0, hints: ["2% of the bill comes off.", "Round to a whole coin."], work: `${b.amount} − ${d} = ${b.amount - d}.`, docs: [] }; } },
    { id: "depreciation", concept: "depreciation", make: s => { if (s.bal.equip <= 0) return null; return { text: `A sprinkler cost <b>${S.R.sprinklerCost}</b> and is expected to last <b>${S.R.sprinklerCost / S.R.depPerWeek} weeks</b>. How much Depreciation does it add to your costs each week?`, answer: S.R.depPerWeek, tol: 0,
        hints: ["Spread the cost evenly over its life.", "Cost ÷ weeks of life."], work: `${S.R.sprinklerCost} ÷ ${S.R.sprinklerCost / S.R.depPerWeek} = ${S.R.depPerWeek} a week.`, docs: [] }; } },
    { id: "breakeven", concept: "breakeven", make: (s, tier) => { tier = tier || 1; const p0 = S.marketPrice(s.day), cut = tier >= 2 ? (p0 - S.R.unitCost >= 4 ? 2 : 1) : 0, p = p0 - cut, dear = tier >= 3 && p - S.R.unitCost - 1 > 0 ? 1 : 0, g = p - S.R.unitCost - dear, w = Math.max(S.R.wageFloor, S.R.upkeep - S.R.sprinklerSaving * s.plots.filter(q => q.sprinkler).length); if (g <= 0) return null;
        return { text: tier === 1 ? `Wages are <b>${w}</b> a week. Each sack sold at today's <b>${p}</b> earns <b>${g}</b> of gross profit. How many sacks a week just to cover the wages?` : tier === 2 || !dear ? `Wages are <b>${w}</b> a week. Grisby undercuts and the going price falls from ${p0} to <b>${p}</b>. A sack costs ${S.R.unitCost}. How many sacks a week now cover the wages?` : `Wages are <b>${w}</b> a week. The price falls from ${p0} to <b>${p}</b> and seed gets 1 dearer, so a sack now costs ${S.R.unitCost + 1}. How many sacks a week cover the wages?`, answer: Math.ceil(w / g), tol: 0, why: { q: "Why does a small price cut raise break-even so much?", opts: ["Wages stay fixed while each sack's contribution shrinks", "Wages rise when prices fall", "Fewer people buy at any lower price"], right: 0 }, hints: ["Wages ÷ gross profit per sack.", "Round up: half a sack doesn't pay anyone."], work: `${w} ÷ ${g} = ${r1(w / g)}, so ${Math.ceil(w / g)} sacks.`, docs: [] }; } },
    { id: "ratio", concept: "ratios", make: s => { const b = S.balanceSheet(s.bal); if (b.currentLiab <= 0) return null; const r = r1(b.currentAssets / b.currentLiab);
        return { text: `Your current assets (Cash, receivables, Inventory) are <b>${b.currentAssets}</b>. Your current liabilities (payables, the loan, the Crown, deposits) are <b>${b.currentLiab}</b>. What's your current ratio, to one decimal?`, answer: r, tol: .05, hints: ["Current assets ÷ current liabilities.", "Under 1.0 means you owe more soon than you hold."], work: `${b.currentAssets} ÷ ${b.currentLiab} = ${r}.`, docs: ["ledger"] }; } },
    { id: "deposit", concept: "accrual", make: s => { const o = S.openOrders(s).find(x => x.paid); if (!o) return null;
        return { text: `${S.NAMES[o.who].split(" ")[0]} paid you a <b>${o.paid}</b> deposit on ${o.sacks} sacks, which you haven't delivered. How much Revenue have you earned from that order so far?`, answer: 0, tol: 0, hints: ["Revenue is earned when the grain is delivered.", "The deposit is Cash, but what is it on the balance sheet?"], work: `0. The ${o.paid} is a liability, Customer deposits, until you deliver.`, docs: ["ledger"] }; } },
    { id: "opportunity", concept: "opportunity", make: (s, tier) => { tier = tier || 1; const c = S.R.unitCost, tp0 = S.traderPrice(s.day), haul = tier >= 2 ? 1 : 0, tp = tp0 - haul; if (s.day < 8 || tp <= c + 1) return null; const p = tier >= 3 ? c + 1 : Math.max(c + 1, tp - 1 - (hash("opp" + s.day) % 2));
        if (tier >= 3) return { text: `A neighbour offers <b>${p}</b> for a spare sack that cost you <b>${c}</b>. The road trader pays <b>${tp0}</b> for the same sack, but the haul costs you <b>${haul}</b>. How much better off are you taking the trader than the neighbour, per sack?`, answer: tp - p, tol: 0, hints: ["The better sale is what the trader pays after the haul.", "Compare it with the neighbour's offer, not with the cost."], work: `The trader nets ${tp0} − ${haul} = ${tp}. Against the neighbour's ${p} that is ${tp - p} more per sack. The cost of ${c} does not enter into it.`, docs: [] };
        return { text: haul ? `A neighbour offers <b>${p}</b> for a spare sack that cost you <b>${c}</b>. The road trader pays <b>${tp0}</b>, but the haul costs you ${haul}. What is the lowest price worth taking?` : `A neighbour offers <b>${p}</b> for a spare sack that cost you <b>${c}</b>. The road trader pays <b>${tp}</b> for the same sack. What is the lowest price worth taking?`, answer: tp, tol: 0, why: { q: "Why is the cost not the floor?", opts: ["Because cost is sunk and only the best alternative sale matters now", "Because the neighbour always pays too little", "Because the trader is more honest"], right: 0 }, hints: ["Your cost isn't the floor once a better sale is on offer.", "What would the same sack fetch from the trader?"], work: `The trader pays ${tp} for the same sack, so anything at or below ${tp} gives up a better sale. The floor is ${tp}, not the ${c} it cost.`, docs: [] }; } },
    { id: "tvmflip", concept: "tvm", make: (s, tier) => { tier = tier || 1; const R = S.R, rate = S.terms(s).rateBp, base = 200, wks = tier >= 2 ? 2 : 1, fee = tier >= 3 ? 2 : 0, disc = Math.round(base * R.discPct), carry = Math.round(base * (1 - R.discPct) * rate / 10000 * wks) + fee; if (disc === carry) return null;
        return { choices: ["Take the discount (borrow from Ezra for the week)", "Skip it and keep the Cash"], answer: disc > carry ? 0 : 1, why: { q: "What makes the discount worth taking or not?", opts: ["Compare what paying early saves with what the borrowed Cash costs for the time you wait", "A discount is always worth taking", "Borrowing is always worse than waiting"], right: 0 }, text: `Tomas takes ${Math.round(R.discPct * 100)}% off a ${base} bill if you pay ${wks === 1 ? "a week" : "two weeks"} early. Ezra charges <b>${rate / 100}%</b> a week for Cash today${fee ? `, plus a flat ${fee} to open the loan` : ""}. Which is cheaper?`,
          hints: ["The discount is what paying early saves.", "Ezra's interest on the money you'd borrow for the week is what it costs."], work: `The discount is ${disc}. Ezra's interest on ${base - disc} at ${rate / 100}% for ${wks === 1 ? "a week" : "two weeks"}${fee ? ` plus the ${fee} fee` : ""} is ${carry}. ${disc > carry ? "The discount is bigger: take it." : "The interest is bigger: keep the Cash."} If the rate moves, so does the answer.`, docs: [] }; } },
    { id: "scaling", concept: "overtrading", make: (s, tier) => { tier = tier || 1; const b = S.balanceSheet(s.bal), tied = b.inv + b.ar - b.ap - b.deposits; if (tied <= 0) return null;
        if (tier >= 3 && b.ar > 0) { const t3 = 2 * b.inv + 4 * b.ar - 2 * b.ap - 2 * b.deposits; return { text: `Today you hold inventory <b>${b.inv}</b>, receivables <b>${b.ar}</b>, payables <b>${b.ap}</b>, deposits <b>${b.deposits}</b>. You double your sales, and customers take twice as long to pay. About how much is tied up now?`, answer: t3, tol: 0, hints: ["Inventory, payables and deposits double with sales.", "Receivables double with sales and double again with the wait."], work: `2×${b.inv} + 4×${b.ar} − 2×${b.ap} − 2×${b.deposits} = ${t3}. Volume and days multiply: slower customers hurt as much as more of them.`, docs: ["ledger"] }; }
        if (tier === 2) return { text: `Inventory plus receivables, less what you owe suppliers and customers, is <b>${tied}</b> today. If your sales rise by half, about how much is tied up?`, answer: Math.round(1.5 * tied), tol: 1, hints: ["The gap grows in step with sales.", "Half as much again."], work: `${tied} × 1.5 = ${Math.round(1.5 * tied)}.`, docs: ["ledger"] };
        return { text: `Inventory plus receivables, less what you owe suppliers and customers, is <b>${tied}</b> today: the Cash tied up in sacks and invoices. If you double your sales, about how much is tied up?`, answer: 2 * tied, tol: 0, hints: ["The gap grows in step with sales.", "Double the sales, double the sacks and invoices waiting to turn into Cash."], work: `${tied} × 2 = ${2 * tied}. The gap scales with sales and only comes back when growth stops.`, docs: ["ledger"] }; } },
    { id: "ev", concept: "ev", make: (s, tier) => { tier = tier || 1; const c = S.R.unitCost, n = 20 + 5 * (hash("ev" + s.day) % 5), cost = n * c, win = tier >= 2 ? .6 : .7, mult = tier >= 3 ? 1.5 : 2, ev = Math.round(win * (mult - 1) * cost - (1 - win) * cost); return { text: `A caravan will carry <b>${n}</b> sacks, which cost you ${cost}. ${Math.round(win * 100)}% of the time they sell for ${mult === 2 ? "double" : "one and a half times"} that; ${Math.round((1 - win) * 100)}% of the time bandits take everything. What is the expected gain, in coins?`, answer: ev, tol: 0, why: { q: "Why can a bet with a good average still be wrong?", opts: ["The average only holds over many tries; one bad draw can ruin a farm that cannot repeat it", "The average is always wrong", "Bandits are unlikely"], right: 0 },
        hints: ["Weigh each outcome by its chance: gain on 70%, loss on 30%.", "The gain is what it sells for minus the cost; the loss is the whole cost."], work: `${win} × ${Math.round((mult - 1) * cost)} − ${r1(1 - win)} × ${cost} = ${ev}.`, docs: [] }; } },
    { id: "ruin", concept: "ev", make: s => { const f = S.crownFund(s), c = S.R.unitCost, n = 20 + 5 * (hash("ruin" + s.day) % 5), cost = n * c, safe = f.net - cost >= f.crown; return { choices: ["Safe: I'd still cover the Crown", "Risky: I could fall short"], answer: safe ? 0 : 1,
        text: `The Crown wants <b>${f.crown}</b>. What you could pay with, less what you owe, is <b>${f.net}</b>. A caravan promises a gain on average, but it could lose all <b>${cost}</b> of grain. Is it safe to send it?`, hints: ["Take the worst case off what you hold.", "Is it still enough for the Crown?"], work: `${f.net} − ${cost} = ${f.net - cost}, against the Crown's ${f.crown}. ${safe ? "Still enough: the loss wouldn't ruin you." : "Not enough: a positive average doesn't help if the worst case ends the farm."}`, docs: [] }; } },
    // Decisions, not sums: each puts two real ways of paying side by side, on the numbers of the player's own books.
    { id: "fund9", concept: "tvm", make: s => { const t = S.terms(s), R = S.R, n = 9, cost = n * R.seedCost, owed = -s.bal.ap; if (!t.apDays || owed + cost > t.apLimit || t.loanLimit + s.bal.loan < cost) return null;
        const w = Math.round(cost * t.rateBp / 10000), disc = Math.round(cost * R.discPct), ez = 2 * w;
        return { choices: ["Buy the 9 packets on account (Tomas, 14 days)", `Borrow ${cost} from Ezra and pay Cash`], answer: 0, text: `You need ${n} packets (<b>${cost}</b>). Tomas will carry it on account for 14 days free, or Ezra will lend you ${cost} at <b>${t.rateBp / 100}%</b> a week and you pay Tomas Cash. Which costs you less over the next two weeks?`,
          hints: ["Credit from a supplier has no interest; a loan from Ezra does.", "How many pay-days does Ezra's interest run for in two weeks?"], work: `On account costs nothing for 14 days (and ${disc} less if you pay Tomas inside 7). Ezra's ${cost} costs ${w} a week: about ${ez} over two weeks. Supplier credit is the cheapest money there is, which is why it is limited (${t.apLimit} for you) and why paying it late costs you the credit.`, docs: [] }; } },
    { id: "repay100", concept: "tvm", make: s => { const owed = -s.bal.loan, b = s.bills.find(x => S.discNow(s, x) > 0); if (owed <= 0 || !b) return null; const amt = Math.min(100, owed, b.amount), f = S.loanFacts(s, amt), d = Math.round(amt * S.R.discPct), e = f.net;
        if (e === d) return null;
        return { choices: [`Repay ${amt} of Ezra's loan`, `Pay ${amt} of Tomas's bill early for the 2% off`], answer: e > d ? 0 : 1, text: `You have ${amt} spare. Ezra is owed <b>${owed}</b> at <b>${f.rateBp / 100}%</b> a week; Tomas has a bill you could pay early for 2% off. Where does ${amt} of Cash save you more?`,
          hints: ["Repaying Ezra stops interest every pay-day left in the season, less any early-repayment fee.", "Paying Tomas early saves the discount once."], work: `Repaying Ezra saves ${f.weekly} a week for ${f.paydays} pay-days = ${f.saved}${f.fee ? `, less a ${f.fee} early-repayment fee = ${e}` : ""}. Paying Tomas early saves ${d}, once. ${e > d ? "Ezra's debt is the dearer money: repay it first." : "The discount is bigger: take it."} When the rate or the fee changes, so can the answer.`, docs: [] }; } },
  ];
  // choose today's problem: concepts you have met but not mastered come up most; nothing you were asked in the last three days; the same day always picks the same one
  function pick(s, level, allow) {
    s.practice = s.practice || { streak: 0, best: 0, favour: 0, recent: [], done: {}, log: [] }; const p = s.practice, W = { unseen: 0, introduced: 1.6, practiced: 1.1, mastered: .35 };
    const tierOf = c => ({ practiced: 2, mastered: 3 })[level ? level(c) : "introduced"] || 1; // harder as you master a concept (Season 1 is easy; the ramp is the point)
    const cands = BANK.map(b => ({ b, q: b.make(s, tierOf(b.concept)) })).filter(x => x.q && (!allow || allow(x.b.concept)) && !p.recent.slice(-3).includes(x.b.id));
    if (!cands.length) return null; const score = x => (W[level ? level(x.b.concept) : "introduced"] || .6) + (hash(x.b.id + ":" + s.day) % 100) / 400;
    cands.sort((a, b) => score(b) - score(a)); const c = cands[0]; return Object.assign({ id: c.b.id, concept: c.b.concept, tier: tierOf(c.b.concept) }, c.q);
  }
  // "which of these two offers puts more Cash in the chest by the end of the season?" Cash comes the day a buyer pays: delivery on the due day plus the terms; later than day 28 is not Cash yet.
  function compare(s) {
    const offers = s.offers.filter(o => !o.deposit || true).slice(0, 4); if (offers.length < 2) return null;
    const a = offers[0], b = offers.find(o => o !== a && (o.terms !== a.terms || o.price !== a.price) ) || offers[1], cash = o => { const day = o.due + (o.terms || 0), net = o.sacks * o.price; return { day, in28: day <= S.R.days, cash: day <= S.R.days ? net : 0, value: net }; };
    const A = cash(a), B_ = cash(b); const label = (o, c) => `${S.NAMES[o.who].split(" ")[0]}: ${o.sacks} sacks at ${o.price} (${o.value || o.sacks * o.price}), ${o.terms ? `paid ${o.terms} days after delivery` : "Cash on delivery"}, due day ${o.due}`;
    const best = A.cash === B_.cash ? 2 : A.cash > B_.cash ? 0 : 1;
    return { id: "compare", concept: "wc", offers: [a, b], labels: [label(a, A), label(b, B_)], cash: [A.cash, B_.cash], answer: best,
      text: `Two offers are on the table, and you can only grow for one:<br><b>A</b> ${label(a, A)}<br><b>B</b> ${label(b, B_)}<br>Which puts <b>more Cash in the chest by the end of spring (day ${S.R.days})</b>?`,
      work: `A: ${A.in28 ? `${A.cash} in Cash on day ${A.day}` : `${A.value} of Revenue but the Cash arrives on day ${A.day}: not by day ${S.R.days}`}. B: ${B_.in28 ? `${B_.cash} in Cash on day ${B_.day}` : `${B_.value} of Revenue but the Cash arrives on day ${B_.day}: not by day ${S.R.days}`}. Revenue isn't Cash until they pay.` };
  }
  const available = (s, level, allow) => { s.practice = s.practice || { streak: 0, best: 0, favour: 0, recent: [], done: {}, log: [] }; return s.practice.done[s.day] ? null : pick(s, level, allow); };
  // record the result of a problem: a streak of consecutive days, favours for right answers on your own
  function record(s, prob, right, walked) {
    const p = s.practice = s.practice || { streak: 0, best: 0, favour: 0, recent: [], done: {}, log: [] }; p.done[s.day] = right ? 2 : 1; p.recent.push(prob.id); if (p.recent.length > 8) p.recent.shift();
    const yesterday = p.done[s.day - 1] || p.done[s.day - 2]; if (right) { p.streak = yesterday ? p.streak + 1 : 1; p.best = Math.max(p.best, p.streak); if (!walked) p.favour++; } else if (!yesterday) p.streak = 0;
    p.log.push({ day: s.day, id: prob.id, right: !!right, walked: !!walked }); return p;
  }
  return { BANK, pick, available, compare, record, ids: BANK.map(b => b.id) };
})();
